version: '3'
services:

  api:
    container_name: eve-api
    image: "273325000860.dkr.ecr.us-west-2.amazonaws.com/casey-demo:api-release"
    ports:
      - "8080:5000"
    networks:
      - casey

  db:
    image: mongo
    networks:
      - casey


networks:
  casey: