version: '3'
services:

  lambda:
    container_name: codepilot-lambda
    image: "273325000860.dkr.ecr.us-west-2.amazonaws.com/codepilot:lambda-latest"
    networks: 
      - codepilot
    volumes:
      - ../lambda/codepylot:/code
    working_dir: /code
    entrypoint: sh /code/start.sh
    ports:
      - 9000:9000

networks:
  codepilot: